
name: 'Medicine Alert'

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  schedule:
    - cron: '00 13 * * *' # UTC+8小时=北京时间 13代表晚上九点
  watch:
    types: [started]
   
jobs:
  checking:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai          
    - name: Get log
      uses: actions/checkout@master
        
    - name: Alert bark
      env:
        BARK: ${{ secrets.BARK }}
      run: |
        curl -X POST "$BARK" -H "Content-Type: application/x-www-form-urlencoded;charset=utf-8" -d "title=Medicine Alert&body=小秘秘该做操啦~&group=lqm服药提醒"

    - name: Alert wechat
      env:
        WECHAT: ${{ secrets.WECHAT }}
      run: |
        curl -X POST "$WECHAT" -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' -d "title=做操提醒&desp=小秘秘该做操啦~"

